/** Cached DOM references. Keep selectors here so markup renames stay localized. */

export const els = {
  playfieldPanel: document.getElementById("playfield-panel"),
  playfield: document.getElementById("playfield"),
  status: document.getElementById("status"),
  menuToggle: document.getElementById("menu-toggle"),
  appMenu: document.getElementById("app-menu"),
  restartBtn: document.getElementById("restart-btn"),
  previewBtn: document.getElementById("preview-btn"),
  toggleHideBackground: document.getElementById("toggle-hide-background"),
  togglePreciseSnap: document.getElementById("toggle-precise-snap"),
  toggleDisablePreview: document.getElementById("toggle-disable-preview"),
  previewModal: document.getElementById("preview-modal"),
  closePreview: document.getElementById("close-preview"),
  winModal: document.getElementById("win-modal"),
  playAgain: document.getElementById("play-again"),
  startModal: document.getElementById("start-modal"),
  startBtn: document.getElementById("start-btn"),
  pieceOptions: document.getElementById("start-modal")?.querySelectorAll(".piece-option") ?? [],
  galleryOptions: document.getElementById("start-modal")?.querySelectorAll(".gallery-option") ?? [],
  previewImage: document.querySelector("#preview-modal .preview-image"),
  appVersion: document.getElementById("app-version"),
  updateBanner: document.getElementById("update-banner"),
  reloadUpdate: document.getElementById("reload-update"),
  clearAreaBtn: document.getElementById("clear-area-btn"),
  basketControls: document.getElementById("basket-controls"),
  addBasketBtn: document.getElementById("add-basket-btn"),
  removeBasketBtn: document.getElementById("remove-basket-btn"),
  zoomControls: document.getElementById("zoom-controls"),
  zoomInBtn: document.getElementById("zoom-in-btn"),
  zoomOutBtn: document.getElementById("zoom-out-btn"),
  zoomResetBtn: document.getElementById("zoom-reset-btn"),
};
